### PR TITLE
Navigator 2

### PR DESCRIPTION
**Pull request by GIfatahTH**

### CODE REVIEW

**Comment by GIfatahTH** [comment]
Hi @amoslai5128 

Could you help me by giving me the code of the example where deep linking and nested routes are not working?

**Comment by GIfatahTH** [comment]
@amoslai5128 
Please take a look at the navigation example gallery and feed me back. 

https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation

**Comment by amoslai5128** [comment]
> Hi @amoslai5128
> 
> Could you help me by giving me the code of the example where deep linking and nested routes are not working?

From my case, I think it's easy to be described by drawing you a screen or picture.


> @amoslai5128 Please take a look at the navigation example gallery and feed me back.
> 
> https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation

OH MY GOD, this is the smartest way to do that!  
I think it must have a promotion at medium.

**Comment by GIfatahTH** [comment]
@amoslai5128 
> From my case, I think it's easy to be described by drawing you a screen or picture if you don't mind.

Please go ahead.

**Comment by amoslai5128** [comment]
> @amoslai5128
> 
> > From my case, I think it's easy to be described by drawing you a screen or picture if you don't mind.
> 
> Please go ahead.

@GIfatahTH, here I am
Untitled

**Comment by amoslai5128** [comment]
> @amoslai5128 Please take a look at the navigation example gallery and feed me back.
> 
> https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation

I've found a bug on ex14_return_data when I got into options page(yep or nope), then I press F5 on the browser the return data seems lost, and through page did pop but nothing shows up.

**Comment by GIfatahTH** [comment]
@amoslai5128 
>I found a bug on ex14_return_data when I got into the options page(yep or nope), then I pressed F5 from the browser, the return data lost, after page popped, nothing shows up.

I think that the expected behavior. I tried it with Flutter api and got the same behavior. This is because the (yep or nope) page when F5 is pressed is no longer create from the `onPressed` callback where we wait for the result.

**Comment by GIfatahTH** [comment]
Hi @amoslai5128 
This is my first attempt to reproduce your use case:

https://github.com/GIfatahTH/ex_navigation_amosali

I concentrated on navigation logic rather than the UI.

**Comment by GIfatahTH** [comment]
@amoslai5128 
Do you have any issue?

Please see the https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation I updated it.

**Comment by amoslai5128** [comment]
> @amoslai5128 Do you have any issue?
> 
> Please see the https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation I updated it.

Thanks, I'll try later soon, just woke up🤣

**Comment by GIfatahTH** [comment]
@amoslai5128 
Can you do me a favor?
If you could modify the read me file of the [navigation example]( https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation) by adding the list of the examples link with short description of each one.

**Comment by amoslai5128** [comment]
> @amoslai5128 Can you do me a favor? If you could modify the read me file of the [navigation example](https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation) by adding the list of the examples link with short description of each one.

Ok, I try to work on that asap

**Comment by amoslai5128** [comment]
> @amoslai5128 Can you do me a favor? If you could modify the read me file of the [navigation example](https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation) by adding the list of the examples link with short description of each one.

I've posted a new readme, please check it out, tell me if there's any problem.

https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation

**Comment by GIfatahTH** [comment]
@amoslai5128 

>@GIfatahTH I've posted a new readme (unfinished), please check it out, let me know if there's any problem.

Very good work. I really appreciate your contribution. Please go ahead.

Inspired for what I did with nav2 examples. I started creating a set of example catalog going from basic to advanced for all states_rebuilder features.

I let you know asap.

**Comment by GIfatahTH** [comment]
@amoslai5128 
Here is the first set of examples
https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex001_00_sync_global_and_local_state

**Comment by amoslai5128** [comment]
> @amoslai5128 Here is the first set of examples https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex001_00_sync_global_and_local_state

The content looks clean and organized, great work.

**Comment by amoslai5128** [comment]
@GIfatahTH 
Please be noticed that some of the indexes are wrong from the file name.

And I think some examples below should be reordered, for less confusing I use [README](https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_006_5_navigation) as the representative:

- 13: 404 Unknown_Routes **-- in front of -->** 09: Authentication & Navigation Guards

- 14: Data Return from a Screen (Basic) **-- follow after -->**  08: Redirection & Return Information

**Comment by amoslai5128** [comment]
And also, would it be a good idea to move the [assets](https://github.com/GIfatahTH/states_rebuilder/tree/master/assets) to another GitHub project and use the links, in order to reduce the package size?

**Comment by GIfatahTH** [comment]
Hi @amoslai5128. Good work :clap: 

I am almost ready to push the next update. 

Similar to what we did with navigation, I added to example sets; one for sync state mutation and the other for async state mutation. They cover the concept of states_rebuilder from basic to advanced.

I account on you to revise them and update their read me, as you did with navigation examples. I really care to see what you understand of them as a permanent user of states_rebuilder.

Also notice that I add an example to navigation examples. It examples 15 for providing InheritedWidget to pushed routes.

**Comment by amoslai5128** [comment]
@GIfatahTH 
I finished the review of Example 001, please take a look at [Readme](https://github.com/GIfatahTH/states_rebuilder/blob/dev/examples/ex001_00_sync_global_and_local_state/README.md)

However, I'm not sure the [section](https://github.com/GIfatahTH/states_rebuilder/blob/dev/examples/ex001_00_sync_global_and_local_state/README.md#basic-level-monocle_face). About the title of DO & DO NOT, since I don't familiar with the `Set of independent states of the same type living in stacked routes:`. You may want to name a better title right there.

**Comment by GIfatahTH** [comment]
@amoslai5128 Thank you very much. You are doing a good job.

I worked hard in coding and when it comes to the documentation I was very exhausted so I did it lazily.

You are helping me a lot.

**Pull request merged**
