### PR TITLE
V. 3.0.0+1

### PR DESCRIPTION
**Pull request by GIfatahTH**
* Add state persistence feature. #134 

* Add `RM.navigate` for simple navigation. #129 
Now, we use:
```dart
MaterialApp(
  navigatorKey : RM.navigate.navigatorKey,
  //
)

//to  navigate:
* RM.navigator.to(Page1());
* RM.navigator.toNamed('/page1');
* RM.navigator.toReplacement(Page1());
* RM.navigator.toReplacementNamed('/page1');
* RM.navigator.toAndRemoveUntil(Page1(), '/page2');
* RM.navigator.pushNamedAndRemoveUntil('/page1', '/page2');
* RM.navigator.back();
* RM.navigator.backUntil('/page2');
* RM.navigator.backAndToNamed('/page2');
//To show dialogs, menu and bottom sheets
* RM.navigator.toDialog => showDialog
* RM.navigator.toCupertinoDialog => showCupertinoDialog
* RM.navigator.toBottomSheet => showModalBottomSheet
* RM.navigator.toCupertinoModalPopup => showCupertinoModalPopup
//To show Scaffold related snackBars, bottom sheets and drawers
* RM.scaffoldShow.bottomSheet => Scaffold.of(context).showBottomSheet,
* RM.scaffoldShow.snackBar => Scaffold.of(context).showSnackBar,
* RM.scaffoldShow.openDrawer => Scaffold.of(context).openDrawer,
* RM.scaffoldShow.openEndDrawer => Scaffold.of(context).openEndDrawer,
```

* Deprecate `RM.navigator`, `RM.Scaffold` and `RM.show`.
* Refactor internal logic to improve performance.

### CODE REVIEW

**Comment by amoslai5128** [comment]
About the Injected.rebuilder

Current:
```
Injected.rebuilder( 
   ()=>  Width(), 
  initState: ().... 
)
```

Ideal:
```
Injected.rebuilder( 
   initState: ().... 
   ()=>  Width(), 
)

And is it possible to rebuilder many injected objects at the same time, just like RMKey? 

[Global, Local].rebuilder(
  shouldRebuild: (models) => [false, true],
  watchMany: (models) => [models[0].state.val,  model[1].state.data], 
  (List<Injected> models) =>  ...{ models[0].state } ....{ models[1].state }
),

```

**Comment by GIfatahTH** [comment]
>Injected.rebuilder( 
   initState: ().... 
   ()=>  Width(), 
)

`()=>  Width(),` is a positional parameter and `initState` is a named parameter, positional parameter must take the first place.


>[Global, Local].rebuilder(
  shouldRebuild: (models) => [false, true],
  watchMany: (models) => [models[0].state.val,  model[1].state.data], 
  (List<Injected> models) =>  ...{ models[0].state } ....{ models[1].state }
),

Good idea!. With some litte change:

```dart
final global = RM.inject(...);
final local= RM.inject(...);

[global, local].rebuilder(
()=> ..global.state .. {local.state},
  shouldRebuild: () => ...,
  watch: () =>  ...
)
Similar with whenRebuilder and whenRebuilderOR
[global, local].whenRebuilder(
...
 )
```

**Comment by GIfatahTH** [comment]
I added the requested feature,
https://github.com/GIfatahTH/states_rebuilder/blob/v.-3.0.0%2B1/states_rebuilder_package/lib/src/injected/injected_base_extension.dart

**Comment by amoslai5128** [comment]
> I added the requested feature,
> https://github.com/GIfatahTH/states_rebuilder/blob/v.-3.0.0%2B1/states_rebuilder_package/lib/src/injected/injected_base_extension.dart

Thank you!  And also, I'm thinking about is it a good idea to design and poster image for putting on the .Pub.
I can design it with my friend if you wish, when will you release this beta btw? 

Some good example like:
1. https://pub.dev/packages/get  
2. https://redux.js.org/    (Those four items)

**Comment by GIfatahTH** [comment]
@amoslai5128 
Thank you very much for your contribution which I appreciate very much. It makes the package more beautiful.

This version is now ready to be published. My first intention is to publish it within the next two hours. But your idea of a poster image (and maybe a logo of the library,) is a very good idea.

**Comment by amoslai5128** [comment]
> @amoslai5128
> Thank you very much for your contribution which I appreciate very much. It makes the package more beautiful.
> 
> This version is now ready to be published. My first intention is to publish it within the next two hours. But your idea of a poster image (and maybe a logo of the library,) is a very good idea.

You're welcome, I think this library is the best as always 😸. Yes, I shall design tow images, which are logo and simple but clear poster. What's your colour preferences? Or up to the objective feeling of design? 

In the poster there should focus for three to four key points / advantage, any advice?

**Comment by amoslai5128** [comment]
And also, please take a look into the basic use cade part from the readme I commit, I'm not sure it's the best version.

**Comment by amoslai5128** [comment]
And one more thing, it should be on next release;
The redo undo in setSate can be done with the current State?
Now:

serviceState.setState(
                    (s) => serviceState.canUndoState? serviceState.undoState(
Ideal:
serviceState.setState(
                    (s) => s.canUndoState? s.undoState() : null )

Or even nicer:
serviceState.setState(
                    (s) => s.tryUndoState()    // Just like num.tryParse()

**Comment by GIfatahTH** [comment]
>What's your color preferences? Or up to the objective feeling of design?

Let's see what can the designer do.

**Comment by GIfatahTH** [comment]
>In the poster there should focus for three to four key points / advantages, any advice?

Here are some. I am open to all popositions. I want to see yours

* Business logic:
Use pure dart class.
```dart
class MyModel(){
  //Can return any type, futures and streams included
  someMethod(){ ... }
}
```

*To inject it:
```dart
//Defined globally, as class field or even inside build method.
final model = RM.inject<MyModel>(
    ()=>MyModel(),
    //After initialized, it preserves the state it refers to until it is disposed
    onInitialized : (MyModel state) => print('Initialized'),
    //Default callbacks for side effects.
    onWaiting : () => print('Is waiting'),
    hasData : (MyModel data) => print('Has data'),
    hasError : (error, stack) => print('Has error'),
    //It is disposed when no longer needed
    onDisposed: (MyModel state) => print('Disposed'),
);
```

* To mock it in test:
```dart
model.injectMock(()=> MyMockModel());
```
Similar to `RM.inject` there are:
```dart
RM.injectFuture, RM.injectStream, RM.injectComputed and RM.injectFlavor.
```

* To listen to an injected model:
- Rebuild when model has data only:
```dart
model.rebuilder(()=> Text('${model.state}')); 
```
-Handle all possible async status:
```dart
model.whenRebuilder(
    isIdle: ()=> Text('Idle'),
    isWaiting: ()=> Text('Waiting'),
    hasError: ()=> Text('Error'),
    hasData: ()=> Text('Data'),
)
```

* To listen to many injected models and exposes and merged state:
```dart
[model1, model1 ..., modelN].whenRebuilder(
    isWaiting: ()=> Text('Waiting'),//If any is waiting
    hasError: ()=> Text('Error'),//If any has error
    isIdle: ()=> Text('Idle'),//If any is Idle
    hasData: ()=> Text('Data'),//All have Data
)
```

* To mutate the state and notify listener:
```dart
//Direct mutation
model.state= newState;
//or for more options
model.setState(
  (s)=>s.someMethod()
  debounceDelay=500,
);
```
* To undo and redo immutable state:
```dart
model.undoState();
model.redoState();
```

* To navigate, show dialogs and snackBars without `BuildContext`:
```dart
RM.navigate.to(HomePage());

RM.navigate.toDialog(AlertDialog( ... ));

RM.scaffoldShow.snackbar(SnackBar( ... ));
```

**Comment by GIfatahTH** [comment]
>Now:
serviceState.setState(
(s) => serviceState.canUndoState? serviceState.undoState() : null )
Ideal:
serviceState.setState(
(s) => s.canUndoState? s.undoState() : null )
Or even nicer:
serviceState.setState(
(s) => s.tryUndo() // Or tryUndoState() , Just like num.tryParse()

What's the point doing it inside setState, why not doing it outside?

**Comment by amoslai5128** [comment]
> > Now:
> > serviceState.setState(
> > (s) => serviceState.canUndoState? serviceState.undoState() : null )
> > Ideal:
> > serviceState.setState(
> > (s) => s.canUndoState? s.undoState() : null )
> > Or even nicer:
> > serviceState.setState(
> > (s) => s.tryUndo() // Or tryUndoState() , Just like num.tryParse()
> 
> What's the point doing it inside setState, why not doing it outside?

Ok, you're right, but do I still need model.canUndoState? model.undoState() : null? Or simply use model.reDoState?

**Comment by amoslai5128** [comment]
> > What's your color preferences? Or up to the objective feeling of design?
> 
> Let's see what can the designer do.

I'm marking on it, I shall give you the logo today

**Comment by GIfatahTH** [comment]
> Ok, you're right, but do I still need model.canUndoState? model.undoState() : null? Or simply use model.unDoState?

No you don't have to check canUndoState each time? use canUndoState if you want to change the UI for example deactivating a button. otherwise, it is not necessary.

**Comment by amoslai5128** [comment]
WhatsApp Image 2020-09-12 at 10 06 19 PM (1)
WhatsApp Image 2020-09-12 at 11 08 12 PM
WhatsApp Image 2020-09-12 at 11 13 20 PM

**Comment by amoslai5128** [comment]
About the poster, I think it might be a good idea to state it in 4 points, they are:

1. Performance - (a) Strictly rebuild control (b) Immutable / Mutable states support (c) Acchive business logic in pure Dart.

2. Code Clean - (a)  Zero Boilerplate (b) No  annotation & code-generation  (c) Separation of UI & business logic

3. User Friendly - (a) Built-in dependency injection system (b) *SetState in StatelessWidget.   (c) Hot pluggable Stream / Futures (d) Easily Redo / Undo

4. Maintainable - (a) Easy to test, mock the dependencies (b) Built-in debugging print function (c) Capable for complex apps

What do you think? 👍

**Comment by GIfatahTH** [comment]
>Here are the logos, I think the black one (A2) looks more consistent and mysterious, while the white one (A3) looks more concise.
Very few packages would use black as their logo, it makes you more special.
The Logo design used the combination of "S"tates_"r"ebuilder. After the logo is chosen, the poster will follow the logo's theme.

Great job @amoslai5128 , I can't say more. Go with consistency and mystery. What about sharp edges especially on the right side!

**Comment by GIfatahTH** [comment]
>About the poster, I think it might be a good idea to state it in 4 points, they are:

I am about to finish the part of state persistence in local storage.  I think we can add it.

**Comment by amoslai5128** [comment]
WhatsApp Image 2020-09-12 at 11 51 55 PM (1)
WhatsApp Image 2020-09-12 at 11 51 55 PM

**Comment by amoslai5128** [comment]
> > About the poster, I think it might be a good idea to state it in 4 points, they are:
> 
> I am about to finish the part of state persistence in local storage. I think we can add it.

Yes, how do you describe about it?

**Comment by amoslai5128** [comment]
I'm sending you the source file

**Comment by GIfatahTH** [comment]
>Yes, how do you describe about it?

User Friendly - 
(a) Built-in dependency injection system
(b) *SetState in StatelessWidget.
(c) Hot-pluggable Stream / Futures
(d) Easily Redo / Undo
(c) Persisting the State to the Local Storage

where navigation dand showiing dialogs without buildcontext

**Comment by amoslai5128** [comment]
> > Yes, how do you describe about it?
> 
> User Friendly -
> (a) Built-in dependency injection system
> (b) *SetState in StatelessWidget.
> (c) Hot-pluggable Stream / Futures
> (d) Easily Redo / Undo
> (c) Persisting the State to the Local Storage
> 
> where navigation dand showiing dialogs without buildcontext

I message you the link

**Comment by GIfatahTH** [comment]
Folder is empty

**Comment by GIfatahTH** [comment]
Got it! 👍

**Comment by amoslai5128** [comment]
> > Here are the logos, I think the black one (A2) looks more consistent and mysterious, while the white one (A3) looks more concise.
> > Very few packages would use black as their logo, it makes you more special.
> > The Logo design used the combination of "S"tates_"r"ebuilder. After the logo is chosen, the poster will follow the logo's theme.
> 
> Great job @amoslai5128 , I can't say more. Go with consistency and mystery. What about sharp edges especially on the right side!

The sharp edges version will come out tmr, with the poster. If you're going to release soon, just use the black one.

**Comment by GIfatahTH** [comment]
>The sharp edges version will come out tmr, with the poster. If you're going to release soon, just use the black one.

Yes, you are right. Would you add it to the readme file?

I really appreciate the time you spent with me.

**Comment by amoslai5128** [comment]
> > The sharp edges version will come out tmr, with the poster. If you're going to release soon, just use the black one.
> 
> Yes, you are right. Would you add it to the readme file?
> 
> I really appreciate the time you spent with me.
 
You're welcome, it's hoped that more developers will be attracted to come.
Oh, can you add it, since I've already closed my computer. 
Just use HTML formats on the readme, you can copy from the singleton Div. So that the logo can be centre.

**Comment by amoslai5128** [comment]
I think the white style one can be used in dark theme github / flutter pub
Logo-Black
WhatsApp Image 2020-09-12 at 11 51 55 PM (1)

**Comment by amoslai5128** [comment]
Hey GlafatahTH, do you see the logo on Pub.dev? https://pub.dev/packages/states_rebuilder
Seems, it's some problem, is the local image path can't show in pub?

**Pull request merged**
