### PR TITLE
fix issue 187

### PR DESCRIPTION
**Pull request by GIfatahTH**

### CODE REVIEW

**Comment by amoslai5128** [comment]
BTW, where should I edit the wiki doc, since I cannot find the edit button or feature.

**Comment by amoslai5128** [comment]
> BTW, where should I edit the wiki doc, since I couldn't find the edit button or feature.

@GIfatahTH

**Comment by GIfatahTH** [comment]
>I might need to install a little library for the markdown language, for showing multiple code blocks, do you agree? Something like this Code Tabs Extension

Yes, go ahead, that would be great.

>BTW, where should I edit the wiki doc, since I couldn't find the edit button or feature.

I don't have any idea on how to edit the wiki docs.

For the moments, I added a `documents` folder in the dev branch.  You can edit the docs there.

**Comment by amoslai5128** [comment]
> > I might need to install a little library for the markdown language, for showing multiple code blocks, do you agree? Something like this Code Tabs Extension
> 
> Yes, go ahead, that would be great.
> 
> > BTW, where should I edit the wiki doc, since I couldn't find the edit button or feature.
> 
> I don't have any idea on how to edit the wiki docs.
> 
> For the moments, I added a `documents` folder in the dev branch. You can edit the docs there.

Thanks, @GIfatahTH, since I'm not a collaborator and I think it'd be better if you allow turning the `Restrict editing to collaborators only` to false, on the GitHub setting of this repo.

ref: https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by amoslai5128** [comment]
@GIfatahTH 
Will these avaiable to next version?
``` dart
//Method-like
myState.rebuild.onData(
    (data) => Text(data),
),

//Method-like    
myState.rebuild.onAll(
    onIdle: () => Text('onIdle'),
    onWaiting: () => Text('onWaiting'),
    onError: (err, errorRefresh) => Text('onError'),
    onData: (data) => Text('{myState.state}'),
),


//Method-like
myState.rebuild.onOrElse(
    onWaiting: () => Text('onWaiting'),
    orElse: (data) => Text('{myState.state}'),
),


//Method-like
[myState1 , myState2].rebuild.onOrElse(
    onWaiting: () => Text('onWaiting'),
    orElse: (data) => Text('$data'),
),
```

**Comment by GIfatahTH** [comment]
>@GIfatahTH
Since I'm editing the readme, I must confirm that will these be available to next version?

Yes, they are available.

>On the other hand, should we mark the On.all as a deprecated syntax (will be replaced at 2 vers later...)?
I think deprecating On.all is a good idea.

**Comment by GIfatahTH** [comment]
>Thanks, @GIfatahTH, since I'm not a collaborator in this repo and I think it'd be better if you allow turning the Restrict editing to collaborators only to false, on GitHub setting of this repo. This will make the GitHub wiki editable for the public, and make the doc improving day by day.

The wiki is open for modification now.

**Comment by amoslai5128** [comment]
> > Thanks, @GIfatahTH, since I'm not a collaborator in this repo and I think it'd be better if you allow turning the Restrict editing to collaborators only to false, on GitHub setting of this repo. This will make the GitHub wiki editable for the public, and make the doc improving day by day.
> 
> The wiki is open for modification now.

@GIfatahTH May you give basic content into the the [Builder section](https://github.com/GIfatahTH/states_rebuilder/wiki/widget_listener_api) about the two new release builders. After that, I'll wrap the old builders into a legacy section.

Btw, can u teach me some examples on setState with stream? I want to add a mini example into the wiki.
```dart
// I remember long time ago, here was an example about using 
// stream to setState, once any error occurred would return the old State.
Final model = RM.injected<int?>(()=> null);

Stream<int?> fetchToState(currentState) async* {
  yield null;
  try {
    yield await fetchAPI();
  } catch (e) {
    yield currentState;
  }
}

// UI button...
    ...
    ()=> model.setState((s) async* {
             yield*  fetchToState(s);
             } ),
// Can I just use this? 
 onPress: ()=> model.setState((s) => fetchToState()),
```

**Comment by amoslai5128** [comment]
And also i think the readme is overall good to understand now, and I'll have few editions within few hours then it's done, when do you consider to push the new version? 

About the wiki doc, I think only the core contents are must and the others can be a on-going update.

This update is really attractive, if there is any article or YouTube video would be great for promotion.

**Comment by amoslai5128** [comment]
Another question about in readme, is now the `On.all()` only used by inside `SideEffect`? It seems a little bit confusing with `OnBuilder`, if it does the only use-case, should we consider rename it to "OnSetState.all()"？
Since I think some people would wrap the On into:
```dart
// Correct:
OnBuilder(
   ....
    sideEffect: SideEffect(
        initState: () => print('initState'),
        onSetState: On(() => print('onSetState')),
        onAfterBuild: On(() => print('onAfterBuild')),
        dispose: () => print('dispose'),
    ),
   .....
),

// Somehow wrong?
```dart
OnBuilder(
    ....
    sideEffect: SideEffect(
        initState: () => On(() => print('onSetState')),    // Any downside if someone wrongly put the `On` in SideEffect
        onSetState: On(() => print('onSetState')),
        onAfterBuild: On(() => print('onAfterBuild')),
        dispose: () => print('dispose'),
    ),
),
```
```



states_rebuilder offers callbacks to handle the state status change. The state status callbacks are conveniently defined using the `On` class with its named constructor alternatives: 
```dart
// Called when notified regardless of state status of the notification
On(()=> print('on'));
// Called when notified with data status
On.data(()=> print('data'));
// Called when notified with waiting status
On.waiting(()=> print('waiting'));
// Called when notified with error status
On.error((err, refresh)=> print('error'));
// Exhaustively handle all four status
On.all(
  onIdle: ()=> print('Idle'), // If is Idle
  onWaiting: ()=> print('Waiting'), // If is waiting
  onError: (err, refresh)=> print('Error'), // If has error 
  onData:  ()=> print('Data'), // If has Data
)
// Optionally handle the four status
On.or(
  onWaiting: ()=> print('Waiting'),
  onError: (err, refresh)=> print('Error'),
  onData:  ()=> print('Data'),
  or: () =>  print('or')
)
```

**Comment by GIfatahTH** [comment]
>@GIfatahTH May you give basic content into the the Builder section about the two new release builders. After that, I'll wrap the old builders into a legacy section.

I refactor all the file see it.

>Btw, can u teach me some examples on setState with stream? I want to add a mini use case into the wiki.

You can simply use  onPress: ()=> model.setState((s) => fetchToState()),

>Another question about in readme, is now the On.all() only used by inside SideEffect in the future? It seems a little bit confusing with OnBuilder？

Yes, you are right. 

This is the SideEffect api.

```dart
    sideEffects: SideEffects(
        initState: () => print('initState'),
        onSetState: (snapState) => print('onSetState'),
        onAfterBuild: () => print('onAfterBuild'),
        dispose: () => print('dispose'),
    ),
```

I plan to deprecate all `onSetState` in favor of `SideEffects`, so that one no longer use `On` to avoid confusion.

**Pull request merged**
