### PR TITLE
Fix logo missing URL in Pub Dev

### PR DESCRIPTION
**Pull request by amoslai5128**

### CODE REVIEW

**Comment by amoslai5128** [comment]
Btw, since the Circle CI is pending in your master, would you create another branch?

**Comment by GIfatahTH** [comment]
@amoslai5128 thanks, I created a dev branch

**Comment by amoslai5128** [comment]
> @amoslai5128 thanks, I created a dev branch

Poster will be making for you, after my works have done. 🌞
Btw, I recently got a question, how to be more efficient in updating multiple items, say ToDo app:
List<Todo> todos;

Old todos = [todo1, todo2, ... todo99];
//Updates might only change for some todos' Bool isCompleted 
New update = [todo5, todo4, todo20, todo30];

Well, the way I used is use 2d looping / 2d mapping for checking every id of updated data with old id. The problems would be each round will check all again the factors.
What I wanna know is any way the next round can skip the pervious factor.

**Comment by GIfatahTH** [comment]
>Well, the way I used is use 2d looping / 2d mapping for checking every id of updated data == old id. The problems would be each round will check all again the factors.
What I wanna know is any way the next round can skip the pervious factor.

Can you explain more?

**Comment by amoslai5128** [comment]
https://github.com/GIfatahTH/states_rebuilder/blob/master/examples/ex_009_1_2_ca_todo_mvc_cloud_firestore_immutable_with_fi/lib/service/todos_state.dart

How will you do if it changes to update many at line 70,  
Here is what I do:
```
static Stream<TodosState> updateTodo(TodosState todosState, List<Todo> newTodos) {
    var cacheTodos = List<Product>.from(state.todos);
    for (todo t in newTodos) {
      cacheTodos =
          cacheProducts.map((old) => old.id == t.id ? t: old).toList();
    }
    yield* _save(state, cacheTodos);
}
```
currentTodos = [todo1 ..... todo99]
newTodos = [todo1, todo5, todo13, todo20]
The problem would be in the for loop, even at round 1 "todo1" is found, it still checks again at round 2. Can "todo1" be skipped checking when it has been found?

**Comment by amoslai5128** [comment]
> > Well, the way I used is use 2d looping / 2d mapping for checking every id of updated data == old id. The problems would be each round will check all again the factors.
> > What I wanna know is any way the next round can skip the pervious factor.
> 
> Can you explain more?

Hello?

**Pull request merged**
