### PR TITLE
About the poster

### PR DESCRIPTION
**Pull request by amoslai5128**
About the poster, do you have any idea? such as the content info.
The style I want to add a little cyberpunk

### CODE REVIEW

**Comment by GIfatahTH** [comment]
@amoslai5128 Please go with your idea and let's see how we can build upon it.

By the way, I added this example, https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_009_1_3_ca_todo_mvc_with_state_persistence.

Please, take a look at it, and feel free to improve the read me and add the chinease localization  to the app to see how well may explanation is.

**Comment by amoslai5128** [comment]
> @amoslai5128 Please go with your idea and let's see how we can build upon it.
> 
> By the way, I added this example, https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_009_1_3_ca_todo_mvc_with_state_persistence.
> 
> Please, take a look at it, and feel free to improve the read me and add the chinease localization to the app to see how well may explanation is.

WoW, how interesting is this update! I noticed the TodoListX using extension offers a better and cleaner option, instead of the old example using class. However, is the extension runtime immutably, and any limitations?

**Comment by GIfatahTH** [comment]
>Oh, btw, should those SharedPreferencesImp.dart, etc.. be inside the Data Source / Infrastructure Layer?

Yes, It should be there.

>However, is the extension runtime immutably, and any limitations?
Yes it immutable object

>I noticed the TodoListX using extension offers a better and cleaner code (make my life easier sob), instead of the old example using class.

Yes in this case extension is better, in other cases class may be better.It depends.

**Comment by amoslai5128** [comment]
> > Oh, btw, should those SharedPreferencesImp.dart, etc.. be inside the Data Source / Infrastructure Layer?
> 
> Yes, It should be there.
> 
> > However, is the extension runtime immutably, and any limitations?
> > Yes it immutable object
> 
> > I noticed the TodoListX using extension offers a better and cleaner code (make my life easier sob), instead of the old example using class.
> 
> Yes in this case extension is better, in other cases class may be better.It depends.

When will you release the upcoming version? I'm trying to finish the poster asap

**Comment by GIfatahTH** [comment]
>When will you release the upcoming version? I'm trying to finish the poster asap

Maybe for tomorrow.

**Comment by amoslai5128** [comment]
well, I think i can get you the poster tonight

**Comment by amoslai5128** [comment]
> > When will you release the upcoming version? I'm trying to finish the poster asap
> 
> Maybe for tomorrow.

Hey GIfatahTH, would you draw me some simple picture about the mechanism of functional injection?

**Comment by GIfatahTH** [comment]
>Hey GIfatahTH, would you draw me some simple pictures about the mechanism of functional injection?

I do not know exactly what do you mean by simple pictures here.

**Comment by amoslai5128** [comment]
> > Hey GIfatahTH, would you draw me some simple pictures about the mechanism of functional injection?
> 
> I do not know exactly what do you mean by simple pictures here.

Like this https://github.com/GIfatahTH/states_rebuilder/raw/dev/assets/01-states_rebuilder_new_reactive_model.png

And I want to beautify it as https://raw.githubusercontent.com/felangel/bloc/master/docs/assets/cubit_flow.png

**Comment by GIfatahTH** [comment]
OK, that needs some creativity and a calm mind that I don't have now. I think I will publish the current update and continue working on the poster so it will be ready for the next update. Do you agree?

**Comment by amoslai5128** [comment]
> OK, that needs some creativity and a calm mind that I don't have now. I think I will publish the current update and continue working on the poster so it will be ready for the next update. Do you agree?

Yes sure

**Comment by GIfatahTH** [comment]
#139 #134

**Pull request merged**
