### PR TITLE
version 5.0.1

### PR DESCRIPTION
**Pull request by GIfatahTH**

### CODE REVIEW

**Comment by amoslai5128** [comment]
@GIfatahTH 
I want to contribute an example like ex_pokemon_app at the upcoming version, it's a simple app that includes searching, fetching API & local storage, bookmark, etc. I think it takes time to do that but everything is as simple as possible.

Do you think it's a good idea?

**Comment by amoslai5128** [comment]
@GIfatahTH Also, should this repo add a license like pub.dev?

**Comment by GIfatahTH** [comment]
@amoslai5128 
>I want to contribute an example like ex_pokemon_app at the upcoming version (maybe ver. 5.2), it's a simple app that includes searching, fetching API & local storage, bookmark, etc. I think it takes time to do that but everything is as simple as possible.

>Do you think it's a good idea?

Yes, It is a good idea, please go ahead .

> Also, should this repo add a license like pub.dev?

How does license in pub.dev loook like?

**Comment by amoslai5128** [comment]
> @amoslai5128
> 
> > I want to contribute an example like ex_pokemon_app at the upcoming version (maybe ver. 5.2), it's a simple app that includes searching, fetching API & local storage, bookmark, etc. I think it takes time to do that but everything is as simple as possible.
> 
> > Do you think it's a good idea?
> 
> Yes, It is a good idea, please go ahead .
> 
> > Also, should this repo add a license like pub.dev?
> 
> How does license in pub.dev loook like?

https://pub.dev/packages/states_rebuilder/license

You can add the license right here:

https://github.com/GIfatahTH/states_rebuilder/community/license/new?branch=master

**Comment by amoslai5128** [comment]
@GIfatahTH When will be the upcoming update?

**Comment by GIfatahTH** [comment]
@amoslai5128 
>When will be the upcoming update?

Sooner

**Pull request closed without merging**
